<?php

/**
 * @file
 * Realization hook_theme()
 */

/**
 * Register template files.
 */
function koval_theme($existing, $type, $theme, $path):array {
  return [
    'koval-page' => [
      'variables' => [
        'text' => NULL,
        'form' => NULL,
        'cats' => NULL,
        'header_table' => NULL,
        'admin_form' => NULL,
      ],
    ],
    'admin-structure-form' => [
      'variables' => [
        'admin_form' => NULL,
      ],
    ],
  ];
};
